# Global
safe:									true
exclude:							[README.md, LICENSE.md, TODO.md, CNAME]
timezone:							Europe/London

# Dependencies
markdown:							kramdown
highlighter:					rouge

# Markdown Processing
kramdown:
  auto_ids:						true
  entity_output:			as_char
  toc_levels:					1..3
  smart_quotes:				lsquo,rsquo,ldquo,rdquo
  input:							GFM
  hard_wrap:					false
  footnote_nr:				1
  footnote_backlink:	▲

# Styling
sass:
  sass_dir:						_sass
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all

# Permalinks
permalink:						pretty

# Setup
title:								"Astra Intranet"
url:									training.astra-alliance.com
baseurl:							/Intranet/
author:
  name:								"Astra Alliance"
  url:								https://github.com/Astra-Alliance
fonts:								"Open+Sans"

# Custom variables
version:							"1.0.0"

# Extras
analytics:
  enable:							false
  id:									"UA-66177219-2"

github:
  repo:								https://github.com/Astra-Alliance/Intranet